@echo off
REM AXIS Language Installer for Windows
REM Version: 1.0.2-beta
REM
REM Usage: install.bat [--user|--system]

setlocal enabledelayedexpansion

echo.
echo ===================================================
echo   AXIS Language Installer (v1.0.2-beta) - Windows
echo ===================================================
echo.

REM Check for Python
where python >nul 2>&1
if %errorlevel% neq 0 (
    echo ERROR: Python is not installed or not in PATH
    echo Please install Python 3.7+ from https://python.org
    pause
    exit /b 1
)

REM Check Python version
for /f "tokens=2" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
echo Found Python %PYTHON_VERSION%

REM Parse arguments
set "INSTALL_MODE=user"
if "%~1"=="--system" set "INSTALL_MODE=system"
if "%~1"=="--user" set "INSTALL_MODE=user"

REM Set installation paths
if "%INSTALL_MODE%"=="system" (
    set "INSTALL_DIR=%ProgramFiles%\AXIS"
    set "BIN_DIR=%ProgramFiles%\AXIS\bin"
    
    REM Check for admin privileges
    net session >nul 2>&1
    if %errorlevel% neq 0 (
        echo ERROR: System installation requires Administrator privileges
        echo Please run this installer as Administrator
        echo Or use: install.bat --user
        pause
        exit /b 1
    )
) else (
    set "INSTALL_DIR=%LOCALAPPDATA%\AXIS"
    set "BIN_DIR=%LOCALAPPDATA%\AXIS\bin"
)

echo Installation mode: %INSTALL_MODE%
echo Install directory: %INSTALL_DIR%
echo.

REM Get script directory (where install.bat is located)
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

REM Check if we're in the installer folder
if exist "%SCRIPT_DIR%\..\compilation_pipeline.py" (
    set "SOURCE_DIR=%SCRIPT_DIR%\.."
) else if exist "%SCRIPT_DIR%\compilation_pipeline.py" (
    set "SOURCE_DIR=%SCRIPT_DIR%"
) else (
    echo ERROR: Cannot find AXIS source files
    echo Please run this installer from the axis-lang directory
    pause
    exit /b 1
)

REM Define required files
set "REQUIRED_FILES=tokenization_engine.py syntactic_analyzer.py semantic_analyzer.py code_generator.py executable_format_generator.py compilation_pipeline.py transpiler.py assembler.py"

REM Verify all required files exist
echo Checking required files...
for %%f in (%REQUIRED_FILES%) do (
    if not exist "%SOURCE_DIR%\%%f" (
        echo ERROR: Missing required file: %%f
        pause
        exit /b 1
    )
)
echo   All required files found.
echo.

REM Create installation directories
echo Creating directories...
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"
if not exist "%BIN_DIR%" mkdir "%BIN_DIR%"
echo   Done.
echo.

REM Copy files
echo Copying files...
for %%f in (%REQUIRED_FILES%) do (
    copy /Y "%SOURCE_DIR%\%%f" "%INSTALL_DIR%\" >nul
    if %errorlevel% neq 0 (
        echo ERROR: Failed to copy %%f
        pause
        exit /b 1
    )
)
echo   Core files copied.

REM Copy CLI wrapper
copy /Y "%SCRIPT_DIR%\axis.bat" "%BIN_DIR%\axis.bat" >nul
echo   CLI wrapper copied.

REM Update CLI wrapper to point to install directory
echo @echo off> "%BIN_DIR%\axis.bat"
echo REM AXIS Language CLI - Windows>> "%BIN_DIR%\axis.bat"
echo REM Auto-generated by installer>> "%BIN_DIR%\axis.bat"
echo setlocal enabledelayedexpansion>> "%BIN_DIR%\axis.bat"
echo set "AXIS_LIB_DIR=%INSTALL_DIR%">> "%BIN_DIR%\axis.bat"
echo.>> "%BIN_DIR%\axis.bat"
echo REM Find Python>> "%BIN_DIR%\axis.bat"
echo where python ^>nul 2^>^&1>> "%BIN_DIR%\axis.bat"
echo if %%errorlevel%% equ 0 (>> "%BIN_DIR%\axis.bat"
echo     set "PYTHON_CMD=python">> "%BIN_DIR%\axis.bat"
echo ) else (>> "%BIN_DIR%\axis.bat"
echo     echo Error: Python not found>> "%BIN_DIR%\axis.bat"
echo     exit /b 1>> "%BIN_DIR%\axis.bat"
echo )>> "%BIN_DIR%\axis.bat"
echo.>> "%BIN_DIR%\axis.bat"
echo %%PYTHON_CMD%% "%%AXIS_LIB_DIR%%\compilation_pipeline.py" %%*>> "%BIN_DIR%\axis.bat"
echo exit /b %%errorlevel%%>> "%BIN_DIR%\axis.bat"

echo   CLI configured.
echo.

REM Add to PATH
echo.
set /p ADD_PATH="Add AXIS to PATH? (recommended) [Y/n]: "
if /i "%ADD_PATH%"=="" set "ADD_PATH=Y"
if /i "%ADD_PATH%"=="Y" (
    if "%INSTALL_MODE%"=="system" (
        REM Add to system PATH
        for /f "tokens=2*" %%a in ('reg query "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" /v Path 2^>nul') do set "CURRENT_PATH=%%b"
        echo !CURRENT_PATH! | find /i "%BIN_DIR%" >nul
        if %errorlevel% neq 0 (
            setx PATH "!CURRENT_PATH!;%BIN_DIR%" /M >nul 2>&1
            echo   Added to system PATH.
        ) else (
            echo   Already in system PATH.
        )
    ) else (
        REM Add to user PATH
        for /f "tokens=2*" %%a in ('reg query "HKCU\Environment" /v Path 2^>nul') do set "CURRENT_PATH=%%b"
        echo !CURRENT_PATH! | find /i "%BIN_DIR%" >nul
        if %errorlevel% neq 0 (
            setx PATH "!CURRENT_PATH!;%BIN_DIR%" >nul 2>&1
            echo   Added to user PATH.
        ) else (
            echo   Already in user PATH.
        )
    )
    echo.
    echo NOTE: You may need to restart your terminal for PATH changes to take effect.
)

echo.
echo ===================================================
echo   AXIS Installation Complete!
echo ===================================================
echo.
echo Installation directory: %INSTALL_DIR%
echo CLI location:          %BIN_DIR%\axis.bat
echo.
echo Quick Start:
echo   axis --help                    Show help
echo   axis run script.axis           Run a script
echo   axis check program.axis        Check syntax
echo   axis info                      Show system info
echo.
echo To uninstall, run: installer\uninstall.bat
echo.

pause
